echo;
echo ==========================================================;
echo ================ZSCALER APP LOG ANALYZER==================;
echo ===============Original By: Gaurav Kamboj=================;
echo ===============Updated By: Jamison Wegman=================;
echo ==========================================================;
echo;
echo ZAPP LOG START_END TIME;
echo ==========================================================;
cat $1/ZSA* |grep $2| head -1;
echo;
cat $1/ZSA* |grep $2| tail -1;
echo;
echo ==========================================================;
echo USER INFO;
echo ==========================================================;
cat $1/ZSATray* |grep $2| grep "username";
echo;
echo ==========================================================;
echo VERSION INFO;
echo ==========================================================;
cat $1/ZSATray* |grep $2| grep "App Version" | sort -u -k9;
echo;
echo ==========================================================;
echo ZAPP START TIME;
echo ==========================================================;
cat $1/ZSAT* |grep $2| grep ZSATUNNEL_START_UP;
echo;
echo ==========================================================;
echo LATEST ERROR STATE;
echo ==========================================================;
cat $1/ZSAT* |grep $2| grep -i get.state | grep _ERROR|sort -u -k2 | tail;
echo;
echo ==========================================================;
echo LATEST STATE;
echo ==========================================================;
cat $1/ZSAT* |grep $2| grep -i get.*state |tail;
echo;
echo ==========================================================;
echo ZIA LATEST URL;
echo ==========================================================;
cat $1/ZSATunnel* |grep $2| grep parseHttpRequest | grep -v ocsp |tail;
echo;
echo ==========================================================;
echo ACCESSED ZPA APP SEGMENTS;
echo ==========================================================;
cat $1/ZSATunnel* |grep $2| grep app_name.tag | tail | sort -u -k18;
echo;
echo ==========================================================;
echo PAC URL;
echo ==========================================================;
cat $1/ZSATunnel* |grep $2| grep -i "PAC URL"| awk {'print $8'} |grep http| sort |uniq;
echo;
echo ==========================================================;
echo NW TYPE;
echo ==========================================================;
cat $1/ZSATunnel* |grep $2| grep getCurrentNetworkType | sort -u -k9 | tail;
echo;
echo ==========================================================;
echo BAD HEALTH TIME;
echo ==========================================================;
cat $1/SATunnel* |grep $2| grep -e ZCPM.*Bad -e ZPHM.*Bad -e ZFHM.*Bad -e ZSAAM.*Bad | tail;
echo;
echo ==========================================================;
echo LATEST FAILURES;
echo ==========================================================;
cat $1/ZSATunnel* |grep $2| grep -e fail -e error -e allow -e Port.*NOT.*found | grep -v "ID\|BRK_MT_CLOSED_FROM_ASSISTANT\|No.*error.*zpn_\|MT_CLOSED_TERMINATED\|No.*zpn.*client.*map" | tail -20 ;
echo;
echo ==========================================================;
echo ==========================================================;
#cd /mnt/c/Users/jwegman/Desktop/zapplogs;
#cp -r $1 /mnt/c/Users/jwegman/Desktop/zapplogs-backup
